---
# tasks file for nginx

- name: Install nginx package  (if not present)
  become: yes
  apt: 
    install_recommends: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - certbot 
      - python3-certbot-nginx
  tags: nginx

- name: Remove default site
  become: yes
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent
  tags: nginx
  notify: Restart nginx
  
- name: Template {{ nginx_site }} to sites-available
  become: yes
  ansible.builtin.template:
    src: "{{ config_nginx_site_src_dir }}{{ nginx_site }}"
    dest: /etc/nginx/sites-available/
    owner: root 
    group: root 
    mode: '0644'
  tags: nginx
  notify: Restart nginx

- name: Enable {{ config_nginx_site }}
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ nginx_site }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site }}"
    owner: root
    group: root
    state: link  
  tags: nginx
  notify: Restart nginx

- name: Install Let's Encrypt
  become: yes
  shell:
    cmd: certbot --nginx -n --agree-tos --email {{ nginx_certbot_email }} -d {{ nginx_certbot_domains }}
  tags: nginx
