---
# tasks file for nginx

- name: Install nginx package  (if not present)
  become: true
  apt: 
    install_recommends: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - certbot 
      - python3-certbot-nginx
  tags: nginx

- name: Copy nginx.conf
  become: true
  copy:
    src: "{{ config_nginx_site_src_dir }}nginx.conf"
    dest: /etc/nginx/nginx.conf
    owner: root 
    group: root 
    mode: '0644'
  notify: Restart nginx
  tags: nginx

- name: Remove default site
  become: true
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
  tags: nginx

- name: Create directory for client certificate
  become: true
  file: 
    path: /etc/nginx/certificates/
    state: directory
    owner: root 
    group: root 
    mode: '0644'
  tags: nginx

- name: Copy {{ nginx_clientca_crt }} 
  become: true
  copy:
    src: "{{ config_nginx_site_src_dir }}{{ nginx_clientca_crt }}"
    dest: /etc/nginx/certificates/clientCA.crt
    owner: root 
    group: root 
    mode: '0644'
  tags: nginx

- name: Template {{ nginx_site }} to sites-available
  become: true
  ansible.builtin.template:
    src: "{{ config_nginx_site_src_dir }}{{ nginx_site }}"
    dest: /etc/nginx/sites-available/
    owner: root 
    group: root 
    mode: '0644'
  tags: nginx

- name: Enable {{ config_nginx_site }}
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ nginx_site }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site }}"
    owner: root
    group: root
    state: link  
  tags: nginx
  notify: Restart nginx

- name: Install Let's Encrypt
  become: true
  shell:
    cmd: certbot --nginx -n --agree-tos --email {{ nginx_certbot_email }} -d {{ nginx_certbot_domains }}
  tags: nginx
