---
# tasks file for mqtt bridge

- name: Install Packages needed for Mi Flora MQTT Bridge
  become: yes
  apt: 
    install_recommends: yes
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3 
      - python3-pip 
      - bluetooth 
      - pi-bluetooth 
      - bluez
      - rfkill # Not strictly needed but convenient
  tags: mi_flora


- name: Create directory for source files
  become: yes
  file: 
    path: /opt/miflora-mqtt-daemon
    state: directory
  tags: mi_flora

# There is probably a better way to ensure that the firewall is enabled again at the end even if something goes wrong
- name: Disable firewall
  become: yes
  ufw:
    state: disabled
  tags: mi_flora


- name: Download source files from github
  become: yes
  git:
      repo: https://github.com/ThomDietrich/miflora-mqtt-daemon.git
      dest: /opt/miflora-mqtt-daemon
      version: 50649b39f30faef6d8e04711e06c13583d16f7f8
  tags: mi_flora


- name: Install
  become: yes
  command: pip3 install -r requirements.txt
  args:
      chdir: /opt/miflora-mqtt-daemon

- name: Copy configuration in place
  become: yes
  ansible.builtin.template:
    src: miflora-mqtt-daemon/config.ini
    dest: /opt/miflora-mqtt-daemon/config.ini

- name: Copy service in place
  become: yes
  copy:
    remote_src: yes
    src: /opt/miflora-mqtt-daemon/template.service
    dest: /etc/systemd/system/miflora.service

- name: Reload service
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: miflora

- name: Enable service 
  become: yes
  ansible.builtin.systemd:
    enabled: yes
    name: miflora


- name: Enable firewall
  become: yes
  ufw:
    state: enabled
  tags: mi_flora
