---
# defaults file for os_services

firewall_inbound_mqtt_port: ""
firewall_inbound_http_port: ""
firewall_inbound_https_port: ""
firewall_outbound_upstream_ip: ""
firewall_outbound_upstream_port: ""
