---
# tasks file for unattended auto update

- name: Install unattended upgrades package  (if not present)
  become: yes
  apt: 
    install_recommends: yes
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - unattended-upgrades 
      - apt-listchanges
      - apticron
  tags: autoupdate

- name: Copy 50unattended-upgrades
  become: yes
  copy: 
    src: autoupdate/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/
    owner: root 
    group: root 
    mode: '0644'
