---
# tasks file for firewall baseline

- name: Install ufw firewall package  (if not present)
  become: yes
  apt: 
    install_recommends: yes
    name: "ufw"
    state: present
  tags: firewall

- name: Default deny incoming
  become: yes
  ufw:
    default: deny
    direction: incoming
  tags: firewall

- name: Default deny outgoing
  become: yes
  ufw:
    default: deny
    direction: outgoing
  tags: firewall

# Important to avoid locking us out
- name: Firewall limit ssh
  become: yes
  ufw:
    rule: limit 
    to_port: ssh
    proto: tcp
  tags: firewall

- name: Allow HTTP
  become: yes
  ufw:
    rule: allow 
    to_port: http
    proto: tcp
  tags: firewall

- name: Allow HTTPS
  become: yes
  ufw:
    rule: allow 
    to_port: https
    proto: tcp
  tags: firewall

- name: Allow DNS connections to DNS server
  become: yes
  ufw:
    rule: allow
    direction: out
    to_ip: "{{ dns_ip }}" 
    to_port: "53"
    proto: udp
  tags: firewall

- name: Allow apt updates to connect to specific IPs
  become: yes
  ufw:
    rule: allow
    direction: out
    to_ip: "{{ item }}" 
    to_port: http
    proto: tcp
  loop: "{{ config_firewall_apt_update_ips }}"    
  tags: firewall

- name: Allow ntp to connect to specific IPs
  # Important since the pi is missing a RTC and easily looses track of time
  become: yes
  ufw:
    rule: allow
    direction: out
    to_ip: "{{ item }}" 
    to_port: ntp
    proto: udp
  loop: "{{ config_firewall_ntp_ips }}"    
  tags: firewall


- name: Allow certbot/letsencrypt connect to specific IPs
  become: yes
  ufw:
    rule: allow
    direction: out
    to_ip: "{{ item }}" 
    to_port: https
    proto: tcp
  loop: "{{ config_firewall_letsencrypt_ips }}"    
  tags: firewall

- name: Allow outbound to downstream service
  become: yes
  ufw:
    rule: allow
    direction: out
    to_ip: "{{firewall_downstream_ip}}"
    to_port: "{{firewall_downstream_port}}"
    proto: tcp
  tags: firewall

- name: Enable firewall
  become: yes
  ufw:
    state: enabled
  tags: firewall

