---
# tasks file for os_servies role

- name: Import firewall tasks
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall
- name: Import autoupdate tasks
  ansible.builtin.import_tasks: autoupdate.yml
  tags: autoupdate
- name: Import SSH tasks
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh
- name: Import rsyslog tasks
  ansible.builtin.import_tasks: rsyslog.yml
  tags: rsyslog
- name: Import fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  tags: fail2ban
