---
# tasks file for os_servies role

- include: firewall.yml
  tags: firewall
- include: autoupdate.yml
  tags: autoupdate
- include: ssh.yml
  tags: ssh
- include: rsyslog.yml
  tags: rsyslog
- include: nginx.yml
  tags: nginx
- include: fail2ban.yml
  tags: fail2ban
#- include: chrony.yml
#  tags: chrony
#- include: unattended-upgrades.yml
#  tags: unattended-upgrades