---
# tasks file for os_servies role

- import_tasks: firewall.yml
  tags: firewall
- import_tasks: autoupdate.yml
  tags: autoupdate
- import_tasks: ssh.yml
  tags: ssh
- import_tasks: rsyslog.yml
  tags: rsyslog
- import_tasks: fail2ban.yml
  tags: fail2ban
