map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/letsencrypt/live/{{ nginx_certbot_primary_domain }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ nginx_certbot_primary_domain }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        ssl_client_certificate /etc/nginx/certificates/clientCA.crt;
        ssl_verify_client on;

        location / {
                proxy_pass http://192.168.1.2:8080;
        }
}

server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
}
