---
# tasks file zigbee2mqtt

- name: Install Packages needed for zigbee2mqtt
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nodejs
      - npm
      - git
  tags: zigbee2mqtt

- name: Create directory for source files
  become: true
  ansible.builtin.file:
    path: /opt/zigbee2mqtt
    state: directory
    owner: "{{ host_alt_user }}"
    group: "{{ host_alt_user }}"
  tags: zigbee2mqtt

# There is probably a better way to ensure that the firewall is enabled again at the end even if something goes wrong
- name: Disable firewall
  become: true
  ufw:
    state: disabled
  tags: zigbee2mqtt

- name: Download source files from github
  ansible.builtin.git:
    repo: https://github.com/Koenkk/zigbee2mqtt.git
    dest: /opt/zigbee2mqtt
    depth: 1
    update: false
    version: HEAD
  tags: zigbee2mqtt,zigbee2mqtt.install

- name: Install dependencies
  ansible.builtin.command: npm ci
  args:
    chdir: /opt/zigbee2mqtt
  tags: zigbee2mqtt,zigbee2mqtt.install

- name: Build
  ansible.builtin.command: npm run build
  args:
    chdir: /opt/zigbee2mqtt
  tags: zigbee2mqtt,zigbee2mqtt.install

- name: Setup configuration.yaml
  become: true
  ansible.builtin.template:
    src: zigbee2mqtt/configuration.yaml.j2
    dest: /opt/zigbee2mqtt/data/configuration.yaml
    backup: true
  changed_when: false
  tags: zigbee2mqtt,zigbee2mqtt.configuration

- name: Setup systemd service
  become: true
  ansible.builtin.template:
    src: zigbee2mqtt/zigbee2mqtt.service.j2
    dest: /etc/systemd/system/zigbee2mqtt.service
  tags: zigbee2mqtt,zigbee2mqtt.service

- name: Reload service
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: zigbee2mqtt
  tags: zigbee2mqtt,zigbee2mqtt.service

- name: Enable service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: zigbee2mqtt
  tags: zigbee2mqtt,zigbee2mqtt.service


- name: Enable firewall
  become: true
  ufw:
    state: enabled
  tags: zigbee2mqtt
