---

- hosts: pi_server
  gather_facts: True
  roles:
    - { role: os_users }
    - { role: os_base }
    - { role: os_kernel }
    - { role: os_base_packages }
    - { role: os_services }

- hosts: http_reverse_proxy_server
  gather_facts: True
  roles:
    - { role: http_reverse_proxy, tags: http_reverse_proxy }

- hosts: mi_flora_server
  gather_facts: True
  roles:
    - { role: mqtt_bridge, tags: mi_flora }
