---
# tasks file mosquitto

- name: Install Packages needed for mosquitto
  become: true
  apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mosquitto
  tags: mosquitto

- name: Touch pwfile
  become: true
  command: "touch /etc/mosquitto/pwfile"
  tags: mosquitto,mosquitto.user

- name: Add user
  become: true
  command: "mosquitto_passwd  -b /etc/mosquitto/pwfile {{zigbee2mqtt_mqtt_username}} {{zigbee2mqtt_mqtt_password}}"
  changed_when: false
  tags: mosquitto,mosquitto.user

- name: Setup global.conf
  become: true
  template:
    src: conf.d/global.conf.j2
    dest: /etc/mosquitto/conf.d/global.conf
    backup: false
  changed_when: false
  tags: mosquitto,mosquitto.configuration

- name: Setup listener.conf
  become: true
  template:
    src: conf.d/listener.conf.j2
    dest: /etc/mosquitto/conf.d/listener.conf
    backup: false
  changed_when: false
  tags: mosquitto,mosquitto.configuration

- name: Setup bridge.conf
  become: true
  template:
    src: conf.d/bridge.conf.j2
    dest: /etc/mosquitto/conf.d/bridge.conf
    backup: false
  changed_when: false
  tags: mosquitto,mosquitto.configuration

- name: Reload service
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: zigbee2mqtt
  tags: mosquitto,mosquitto.configuration,mosquitto.service
