---
# tasks file for os_base_packages

- name: Install OS Base Packages  Debian 10
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - aptitude
      - dnsutils
      - screen
      - python3-apt
      - apt-transport-https
      - debian-archive-keyring
      - locales-all
      - rsync
      - wget
      - curl
      - vim
      - git
      - iotop
  when: ansible_distribution_major_version == "10"
  tags: basepackages

- name: Install OS Base RPi Packages Debian 10
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - dkms
      - console-data
      - xkbset
      - raspberrypi-kernel-headers
      - ttf-mscorefonts-installer
  when:
    - ansible_distribution_major_version == "10"
    - inventory_hostname in groups['pi_server']
  tags: basepackages

- name: Install OS Base Packages Debian 12
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - aptitude
      - dnsutils
      - screen
      - python3-apt
      - debian-archive-keyring
      - locales-all
      - rsync
      - wget
      - curl
      - vim
      - git
      - iotop
  when: ansible_distribution_major_version == "12"
  tags: basepackages

- name: Install OS Base RPi Packages Debian 12
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - dkms
      - xkbset
      - raspberrypi-kernel-headers
      - ttf-mscorefonts-installer
  when:
    - ansible_distribution_major_version == "12"
    - inventory_hostname in groups['pi_server']
  tags: basepackages


- name: Install OS Base Packages Debian 13
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - aptitude
      - dnsutils
      - screen
      - python3-apt
      - debian-archive-keyring
      - locales-all
      - rsync
      - wget
      - curl
      - vim
      - git
      - iotop
  when: ansible_distribution_major_version == "13"
  tags: basepackages

- name: Install OS Base RPi Packages Debian 13
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    rpi_kernel_variant: "{{ ansible_kernel.split('+rpt-')[1] }}"
    packages:
      - dkms
      - xkbset
      - "linux-headers-{{ rpi_kernel_variant }}"
      - ttf-mscorefonts-installer
  when:
    - ansible_distribution_major_version == "13"
    - inventory_hostname in groups['pi_server']
  tags: basepackages