---
# tasks file for os

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Set timezone to '{{ config_timezone }}'
  become: true
  timezone:
    name: "{{ config_timezone }}"
  tags: timezone

- name: Ensure localisation files for system locale '{{ config_system_locale }}' are available
  become: yes
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present
  tags: locale

- name: Ensure localisation files for system language '{{ config_system_language }}' are available
  become: yes
  locale_gen:
    name: "{{ config_system_language }}"
    state: present
  tags: locale

- name: Get current locale and language configuration
  become: yes
  command: localectl status
  register: locale_status
  changed_when: false
  tags: locale

- name: Parse 'LANG' from current locale and language configuration
  become: yes
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
  tags: locale

- name: Parse 'LANGUAGE' from current locale and language configuration
  become: yes
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"
  tags: locale

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  become: yes
  command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  changed_when: locale_lang != config_system_locale or locale_language != config_system_language
  tags: locale

- name: Set Keyboard Layout to {{ config_keyboard_layout }}
  become: yes
  lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBLAYOUT="
    line: "XKBLAYOUT=\"{{config_keyboard_layout}}\""
    state: present
  tags: keyboard

- name: Fixup APT Configs
  become: yes
  copy:
    dest: "/etc/apt/apt.conf.d/99-custom-configs"
    content: |
      Acquire::Languages "none";
      Acquire::ForceIPv4 "true";
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::AutoRemove::RecommendsImportant "false";
      APT::AutoRemove::SuggestsImportant "false";
      Dpkg::options {
          "--force-confdef";
          "--force-confold";
      }
  tags: apt

- name: Fixup APT Cache
  become: yes
  copy:
    dest: "/etc/apt/apt.conf.d/99-custom-cache"
    content: |
      Dir::Cache "/tmp/apt";
      Dir::Cache::archives "/var/cache/apt/archives";
      Dir::Cache::pkgcache "";
      Dir::Cache::srcpkgcache "";
  tags: apt

- name: Select raspbian mirror to {{ config_apt_mirror_url }}
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb) (http.*) ([a-z]*(?!-security)) (.*) (.*) (.*) (.*)$'
    replace: '\1 {{ config_apt_mirror_url }} \3 \4 \5 \6 \7'
  tags: apt-sources


- name: Select raspbian security mirror to {{ config_apt_security_mirror_url }}
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb) (http.*) ([a-z]*(-security)) (.*) (.*) (.*) (.*)$'
    replace: '\1 {{ config_apt_security_mirror_url }} \3 \5 \6 \7 \8'
  tags: apt-sources


- name: obtain system PARTUUID for /boot
  become: yes
  command: "findmnt -no PARTUUID /boot"
  register: var_part_boot
  changed_when: false
  when: ansible_distribution_major_version == "10"
  tags: fstabsetup

- name: obtain system PARTUUID for /boot/firmware
  become: yes
  command: "findmnt -no PARTUUID /boot/firmware"
  register: var_part_boot_firmware
  changed_when: false
  when: ansible_distribution_major_version == "12"
  tags: fstabsetup

- name: Obtain system PARTUUID for /
  become: yes
  command: "findmnt -no PARTUUID /"
  register: var_part_root
  changed_when: false
  tags: fstabsetup

- name: Setup fstab file for {{ ansible_distribution }} {{ ansible_distribution_major_version }}
  become: yes
  template: src={{ item }} dest=/etc/fstab backup=yes
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.fstab.j2"
    - "{{ ansible_distribution }}.fstab.j2"
  changed_when: false
  tags: fstabsetup

- name: Set Swap File Size (256M)
  become: yes
  lineinfile:
    dest: /etc/dphys-swapfile
    regexp: "^CONF_SWAPSIZE=(.*)"
    line: "CONF_SWAPSIZE=256"
  tags: swapsize

- name: Set hostname '{{config_system_hostname}}'
  become: yes
  ansible.builtin.hostname:
    name: "{{config_system_hostname}}"  
  tags: hostname

- name: Update /etc/hosts with '{{config_system_hostname}}'
  become: yes
  replace:
    dest: /etc/hosts
    regexp: "^(127.0.1.1)(\\s)*(raspberrypi)$"
    replace: '\1\2{{config_system_hostname}}'
  tags: hostname

